Bump release 2.22.0

diff --git a/roles/nginx/tune-nginx/templates/bin/keitaro-print_stats_json.j2 b/roles/nginx/tune-nginx/templates/bin/keitaro-print_stats_json.j2
--- a/roles/nginx/tune-nginx/templates/bin/keitaro-print_stats_json.j2
+++ b/roles/nginx/tune-nginx/templates/bin/keitaro-print_stats_json.j2
@@ -220,11 +220,11 @@ main() {
              fcgi "$(fcgi_json)"
 }
 
-# Save stderr the $stderr variable (see https://stackoverflow.com/a/13806684/612799)
+# Save stderr to the $stderr variable (see https://stackoverflow.com/a/13806684/612799)
 { stderr=$(main 2>&1 1>&3-) ;} 3>&1
 
 if [[ "${stderr}" != "" ]]; then
-  echo "There was errors while generating stats.json:" >&2
+  echo "There was error while generating stats.json:" >&2
   echo "${stderr}" >&2
   exit 1
 fi
