Improve keitaro-regenerate_systemd_roadrunner_watcher_path

diff --git a/roles/keitaro.roadrunner-tune/templates/bin/keitaro-regenerate_systemd_roadrunner_watcher_path.j2 b/roles/keitaro.roadrunner-tune/templates/bin/keitaro-regenerate_systemd_roadrunner_watcher_path.j2
--- a/roles/keitaro.roadrunner-tune/templates/bin/keitaro-regenerate_systemd_roadrunner_watcher_path.j2
+++ b/roles/keitaro.roadrunner-tune/templates/bin/keitaro-regenerate_systemd_roadrunner_watcher_path.j2
@@ -16,18 +16,22 @@ read_unit() {
 }
 
 if [[ ! -f "${WATCH_LIST}" ]]; then
-  echo "ERR: watch list ${WATCH} is missing" > /dev/stderr
-  exit 1
+  (>&2 echo "ERR: Watch list ${WATCH_LIST} is missing. Exiting.")
+  exit
 fi
 if [[ ! -f "${UNIT_PATH}" ]]; then
-  echo "ERR: SystemD unit ${UNIT_PATH} is missing" > /dev/stderr
-  exit 1
+  (>&2 echo "ERR: SystemD unit ${UNIT_PATH} is missing. Exiting.")
+  exit
 fi
 
 OLD_CONTENT=$(read_unit)
 NEW_CONTENT=$(refresh "${OLD_CONTENT}")
 
 if [[ "${NEW_CONTENT}" != "${OLD_CONTENT}" ]]; then
+  echo "Regenerating ${UNIT_PATH}"
   echo "${NEW_CONTENT}" > "${UNIT_PATH}"
-  /usr/bin/systemctl daemon-reload
+  /usr/bin/systemctl daemon-reload && /usr/bin/systemctl reload roadrunner
+  echo "Done regenerating ${UNIT_PATH}"
+else
+  echo "Skip regeneration of ${UNIT_PATH}"
 fi
